(load-plugin "core:stdlib")
(load-plugin "core:pickers")
(load-plugin "core:vim-keybind")
(load-plugin "cvlmtg/grep.hume")
(declare-plugin "core:plum")
(declare-plugin "core:lsp")
(declare-plugin "core:git-diff")
(declare-plugin "core:steel-server")

(bind-key! 'normal "space space" "lsp-goto-definition")
(bind-key! 'normal "space a" "picker-grep-selection")
(bind-key! 'normal "space m" "picker-git-modified")
(bind-key! 'normal "space b" "picker-buffers")
(bind-key! 'normal "space f" "picker-files")
(bind-key! 'normal "space d" "lsp-hover")
(bind-key! 'normal "\\" "goto-alternate-file")

(set-option! "whitespace-space" "trailing")
(set-option! "whitespace-tab" "all")
(set-option! "tab-style" "soft")
(set-option! "tab-width" "2")
(set-option! "lsp.inlay-hints" "true")
(set-option! "signcolumn" "always:2")

(configure-statusline!
  '("Position" "steel:git-branch" "FilePath" "Language" "ReadOnly" "DirtyIndicator")
  '()
  '("MacroRecording" "SearchMatches" "Diagnostics" "KittyProtocol" "Separator" "Mode"))
